name: s1media_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  in_app_update: ^4.2.3
  intl: ^0.19.0
  mailer: ^6.1.2
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login_bg.png
    - assets/otp_animation.json

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Variable.ttf