// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJoJKK5IZdvtIpHMWCns8n7Fl4gtDfG8',
    appId: '1:895846201577:web:107841163a04fd140d5878',
    messagingSenderId: '895846201577',
    projectId: 's1media-app',
    authDomain: 's1media-app.firebaseapp.com',
    storageBucket: 's1media-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChNNW-0DiIKRNEkfaiy30P3jbalCJ4oM4',
    appId: '1:895846201577:android:2ff1d11ff6602ad20d5878',
    messagingSenderId: '895846201577',
    projectId: 's1media-app',
    storageBucket: 's1media-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB62lzvzwgLWx_7bkTzPQqVTJF6rQGhcoI',
    appId: '1:895846201577:ios:d1f9a1037baf5e040d5878',
    messagingSenderId: '895846201577',
    projectId: 's1media-app',
    storageBucket: 's1media-app.appspot.com',
    iosBundleId: 'com.s1media.app.s1mediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB62lzvzwgLWx_7bkTzPQqVTJF6rQGhcoI',
    appId: '1:895846201577:ios:d1f9a1037baf5e040d5878',
    messagingSenderId: '895846201577',
    projectId: 's1media-app',
    storageBucket: 's1media-app.appspot.com',
    iosBundleId: 'com.s1media.app.s1mediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJoJKK5IZdvtIpHMWCns8n7Fl4gtDfG8',
    appId: '1:895846201577:web:0a2ff5461360b7ae0d5878',
    messagingSenderId: '895846201577',
    projectId: 's1media-app',
    authDomain: 's1media-app.firebaseapp.com',
    storageBucket: 's1media-app.appspot.com',
  );
}
